### PR TITLE
Add constraint limits

### PR DESCRIPTION
**Pull request by brandonsturgeon**
I know the format looks a bit cursed, but I think it's the best balance of:
 - Maintainability
 - Readability
 - Copy-ability
 - Performance

If you have another suggestion I'm all ears!

### CODE REVIEW

**Comment by wrefgtzweve** [comment]
Instead of wrapping all functions individually they all end up using `CreateKeyframeRope`, would be best to just wrap it at the source once.

**Comment by brandonsturgeon** [comment]
The reason we didn't originally do that was because it wouldn't let us prevent the constraint entirely (we were returning false)

I think instead I'll have it replace the material with something generic but still let them create the rope

**Comment by wrefgtzweve** [comment]
Yeah i do that in mine, i replace it with `cable/cable2`

**Comment by wrefgtzweve** [comment]
I have no idea what wire uses, i tested and `CreateKeyframeRope` didn't work for wire ropes.

**Comment by brandonsturgeon** [comment]
I'll fix wires in a followup PR 👍

**Pull request merged**
